version: '2'
services:
    palan-nginx:
        container_name: palan-nginx
        image: nginx
        external_links:
           - jupyterhub:jupyterhub
           - palan-ldap-admin:ldap-admin
        volumes:
           - ./datarx.cn:/etc/nginx/conf.d/datarx.cn
        extra_hosts:
           - "console:192.168.3.14"
           - "studio:192.168.3.14"
#           - "jupyterhub:192.168.3.14"
#           - "ldap-admin:192.168.3.14"
        environment:
           DOCKER_NETWORK_NAME: jupyterhub-network
        ports:
           - 80:80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/datarx.cn > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

networks:
  default:
    external:
      name: jupyterhub-network